BusTicketReservationSystem/BusTicketReservationSystem/Controllers/PaymentInitiateController.cs
using BusTicketReservationSystem.DataAccessLayer;
using BusTicketReservationSystem.DomainModel.Models;
using BusTicketReservationSystem.RepositoryContract;
using BusTicketReservationSystem.RepositoryLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace BusTicketReservationSystem.Controllers
{
    public class PaymentInitiateController : Controller
    {
        IPaymentInitiateRepository paymentInitiateRepository;
        public PaymentInitiateController()
        {
            paymentInitiateRepository = new PaymentInitiateRepository();
        }
        public ActionResult Amount_Zero()
        {
            return View();
        }
        public ActionResult Index(int id)
        {
            TempData["Id"] = id;
            var amount = paymentInitiateRepository.Amount(id);
            ViewBag.Total = (int)amount;
            if (amount == 0)
            {
                return RedirectToAction("Amount_Zero");
            }
            return View();
        }

        [HttpPost]
        public ActionResult Index(PaymentInitiateModel _requestData)
        {
            try
            {
                int id = (int)TempData["Id"];
                TempData["Id1"] = id;
                var orderModel = paymentInitiateRepository.CreateBill(id, _requestData);
                return View("PaymentPage", orderModel);
            }
            catch(Exception)
            {
                return Content("Some problem has occured!");
            }
            

        }

        [HttpPost]
        public ActionResult Complete()
        {


            string paymentId = Request.Params["rzp_paymentid"];

            string orderId = Request.Params["rzp_orderid"];
            Razorpay.Api.RazorpayClient client = new Razorpay.Api.RazorpayClient(Globals.RazorPayKey, Globals.RazorPaySecret);

            Razorpay.Api.Payment payment = client.Payment.Fetch(paymentId);

            Dictionary<string, object> options = new Dictionary<string, object>();
            options.Add("amount", payment.Attributes["amount"]);
            Razorpay.Api.Payment paymentCaptured = payment.Capture(options);
            string amt = paymentCaptured.Attributes["amount"];

            if (paymentCaptured.Attributes["status"] == "captured")
            {

                return RedirectToAction("Success");
            }
            else
            {
                return RedirectToAction("Failed");
            }


        }
        public ActionResult Success()
        {
            try
            {
                int id = (int)TempData["Id1"];
                paymentInitiateRepository.Success(id);
                return View();
            }
            catch(Exception)
            {
                return View();
            }


        }
        public ActionResult Failed()
        {
            if(TempData["Id1"]==null)
            {
                return View();
            }
            try
            {
                int id = (int)TempData["Id1"];
                paymentInitiateRepository.Failed(id);
                return View();
            }
            catch(Exception)
            {
                return View();
            }
        }
    }
}

BusTicketReservationSystem/BusTicketReservationSystem/Views/PaymentInitiate/Amount_Zero.cshtml
@{
    ViewBag.Title = "Amount_Zero";
}

<link rel="stylesheet" href="~/Content/Amount_zero.css" />
<body>
    <h2>You haven't Selected a Single Seat</h2>
    <a class="btn btn-info" href="~/Route/BusRoutes/">Go Back</a>
</body>

BusTicketReservationSystem/BusTicketReservationSystem/Views/PaymentInitiate/Failed.cshtml
@{
    ViewBag.Title = "Failed";
}
<style>
    /*.backgraoundFailed {
        font-family: Arial, Helvetica, sans-serif;
        margin-top: 50px;
        background: url(https://www.digitalpaymentguru.com/wp-content/uploads/2019/08/Transaction-Failed.png);
        background-repeat: no-repeat;
        object-fit: cover;
        background-size: cover;
        width:50%;*/
        /*
                backdrop-filter: blur(3px);*/
    /*}*/
</style>
<body class="bodyAlign container backgraoundFailed">
    <div class="col-md-12">
        <div class="col-md-5"></div>
        <img src="https://www.digitalpaymentguru.com/wp-content/uploads/2019/08/Transaction-Failed.png" class="col-md-6" style="margin-left:280px;width:700px;height:20%;" />

    </div>
    <div class="col-md-12">
        <div class="col-md-4"></div>
        <a href="~/Home/Index" class="btn btn-primary text-center col-md-6">Back To Home</a>
        <div class="col-md-2"></div>
    </div>
</body>

BusTicketReservationSystem/BusTicketReservationSystem/Views/PaymentInitiate/Index.cshtml
@model BusTicketReservationSystem.DomainModel.Models.PaymentInitiateModel

@{
    ViewBag.Title = "Index";
}

<style>
    .paymentBody {
        background: url(../../images/Paymentform.jpg);
        background-repeat: no-repeat;
        object-fit: cover;
        background-size: cover;
       
    }
    .divDesign
    {
        margin-left:30%;
        margin-top:10%;
    }
    .divH1
    {
        margin-left:16%;
    }
</style>
<body class="bodyAlign container paymentBody">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="divDesign">
            <div class="form-horizontal col-md-6" style="background-color:white;">
                <h2 class="divH1">Fill Payment Details</h2>
                <br />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                <div class="form-group">
                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @*@Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })*@
                        <input type="email" name="Email" class="form-control" id="Email" />
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        <input type="text" name="Amount" id="Amount" value="@ViewBag.Total" class="form-control" readonly />
                        @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-5"></div>
                    <div class="col-md-6">
                        <input type="submit" value="Confirm" class="btn btn-default btn-success" />
                    </div>

                </div>

            </div>
        </div>
    }

    <div>

    </div>

</body>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BusTicketReservationSystem/BusTicketReservationSystem/Views/PaymentInitiate/PaymentPage.cshtml
@model BusTicketReservationSystem.DomainModel.Models.PaymentInitiateModel
@{
    ViewBag.Title = "PaymentPage";
}


<body class="bodyAlign">
    <h2>PaymentPage</h2>
    <button id="rzp-button1" hidden>Pay</button>
    <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
    <script>
var options = {
    "key": "@Html.DisplayFor(model => model.RazorpayKey)", // Enter the Key ID generated from the Dashboard
    "amount": "@Html.DisplayFor(model => model.Amount)", // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise
    "currency": "@Html.DisplayFor(model => model.Currency)",
    "name": "@Html.DisplayFor(model => model.Name)",
    "description": "@Html.DisplayFor(model => model.Description)",
    "image": "../../images/logo.jpg", 
    "order_id": "@Html.DisplayFor(model => model.OrderId)",
    "handler": function (response){
        // After payment successfully made response will come here
        // Set the data in hidden form
        document.getElementById('rzp_paymentid').value = response.razorpay_payment_id;
        document.getElementById('rzp_orderid').value = response.razorpay_order_id;
        // // Let's submit the form automatically
        document.getElementById('rzp-paymentresponse').click();
    },
    "prefill": {
        "name": "@Html.DisplayFor(model => model.Name)",
        "email": "@Html.DisplayFor(model => model.Email)",
        "contact": "@Html.DisplayFor(model => model.PhoneNumber)"
    },
    @*"notes": {
        "address": "@Html.DisplayFor(model => model.Address)"
    },*@
    "theme": {
        "color": "Blue"
    }
};
var rzp1 = new Razorpay(options);
//<!-- onload function -->
window.onload = function(){
    document.getElementById('rzp-button1').click();
};
document.getElementById('rzp-button1').onclick = function(e){
    rzp1.open();
    e.preventDefault();
}
    </script>

    <!-- This form is hidden, and submit when payment successfully made -->
    @using (Html.BeginForm("Complete", "PaymentInitiate"))
    {
        @Html.AntiForgeryToken()

        @Html.Hidden("rzp_paymentid")
        @Html.Hidden("rzp_orderid")
        <input type="submit" id="rzp-paymentresponse" class="btn btn-primary" hidden >
    }
    <div class="text-center">
        
        <h2>Error Occured.Please click below!</h2>
        <a href="~/PaymentInitiate/Failed" class="btn btn-danger">Click Here</a>
    </div>
</body>

BusTicketReservationSystem/BusTicketReservationSystem/Views/PaymentInitiate/Success.cshtml
@{
    ViewBag.Title = "Success";
}
<style>
    .success1 {
        margin-left: 45%;
        margin-top: 13%;
        font-weight: bold;
    }

    .success2 {
        margin-left: 41%;
        /*   margin-top: 18%;*/
        font-weight: bold;
    }
</style>
<link rel="stylesheet" href="~/Content/style.css" />
<h1 class="success1">Success</h1>
<h2 class="success2">Happy Travelling!</h2>



<div class="loop-wrapper">
    <div class="mountain"></div>
    <div class="hill"></div>
    <div class="tree"></div>
    <div class="tree"></div>
    <div class="tree"></div>
    <div class="rock"></div>
    <div class="truck"></div>
    <div class="wheels"></div>
</div>